[package]
name = "val_unc"
version = "0.6.0"
authors = ["Justin Browne <jebdude89@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
rand = { version = "0.7", optional = true }
